 //Category constant types---------
 export const FETCH_CATEGORY_REQUEST='FETCH_CATEGORY_REQUEST'
 export const FETCH_CATEGORY_SUCCESS='FETCH_CATEGORY_SUCCESS'
 export const FETCH_CATEGORY_FAILURE='FETCH_CATEGORY_FAILURE'

 export const SET_CURRENT_CATEGORY='SET_CURRENT_CATEGORY';

 //Product constant types---------
 export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST'
 export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
 export const FETCH_PRODUCT_FAILURE='FETCH_PRODUCT_FAILURE'

 // Cart Constant Type---------------

 export const ADD_TO_CART='ADD_TO_CART';
 export const REMOVE_FROM_CART='REMOVE_FROM_CART';
 export const INCREASE_QUANTITY_OF_PRODUCT='INCREASE_QUANTITY_OF_PRODUCT';
 export const DECREASE_QUANTITY_OF_PRODUCT='DECREASE_QUANTITY_OF_PRODUCT';
 

 //Cart Increase and decrease
